name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    #- name: Ensure go.mod is already tidied
    #  run: go mod tidy && git diff --no-patch --exit-code
    - name: Run unit tests
      run: go test -v ./...
    - name: Build
      run: go build -v ./...
